name: 'action-wait-workflows'
description: 'Waits for workflows to complete for a given commit before proceeding'
author: 'bengreenier-actions'
inputs:
  commit:
    required: true
    description: "The commit to retrieve runs for"
  workflow:
    required: true
    description: "The workflow to wait for"
  workflow_conclusion:
    required: true
    description: "The type of conclusion you desire"
  timeout_ms:
    required: false
    description: "The max number of ms to wait for"
    # 5m
    default: '300000'
runs:
  using: 'node16'
  main: 'dist/index.js'
