name: 'slowpoke2'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  sleep2: # Just a job that takes a while
    runs-on: ubuntu-latest
    steps:
      - run: sleep 3m

